version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - elasticsearch
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Elasticsearch datasource is built-in since Grafana 8.3+, no plugin needed
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    depends_on:
      - elasticsearch
      - api
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - api_logs:/app/logs   # Share the same volume as the API container
    ports:
      - "5044:5044"
      - "9600:9600"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: sanrio_api
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200
    ports:
      - "8000:8000"
    volumes:
      - api_logs:/app/logs   # Use named volume instead of bind mount

volumes:
  es_data:
  api_logs:
  grafana_data:
