apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "api-logs"
    basicAuth: false
    isDefault: true
    jsonData:
      esVersion: "8.15.0"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
      includeFrozen: false
      maxConcurrentShardRequests: 5
    readOnly: false